logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    max-active: 4
    max-idle: 2
    max-wait: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true
    validation-query: SELECT 1
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri:        https://oauth2.googleapis.com/token
            user-info-uri:    https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
server:
  port: ${PORT:8080}
  servlet:
    context-path: /civicfix

project:
  jwt:
    signKey: ${JWT_SECRET}
    expirationMinutes: 1440
  contact:
    email: ${CONTACT_EMAIL}
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
