-- DROP TABLES
DROP TABLE IF EXISTS pointtransactions;
DROP TABLE IF EXISTS survey_response_options;
DROP TABLE IF EXISTS surveyresponses;
DROP TABLE IF EXISTS survey_options;
DROP TABLE IF EXISTS surveys;
DROP TABLE IF EXISTS postvotes;
DROP TABLE IF EXISTS posts_files;
DROP TABLE IF EXISTS posts_images;
DROP TABLE IF EXISTS related_posts;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

-- USERS
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(60) NOT NULL,
    password VARCHAR(60) NOT NULL,
    firstName VARCHAR(60) NOT NULL,
    lastName VARCHAR(60),
    email VARCHAR(60) NOT NULL,
    avatar VARCHAR(255) NOT NULL,
    avatarId VARCHAR(255),
    role SMALLINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    googleId VARCHAR(255)
);

-- POSTS
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    location VARCHAR(120) NOT NULL,
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    date TIMESTAMP,
    category VARCHAR(50) NOT NULL,
    userId BIGINT NOT NULL,
    solved BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_posts_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

-- RELATED POSTS
CREATE TABLE related_posts (
    postId BIGINT NOT NULL,
    id BIGINT,
    title VARCHAR(255),
    PRIMARY KEY (postId, id),
    CONSTRAINT fk_related_posts_post FOREIGN KEY (postId) REFERENCES posts(id)
);

-- POSTS_IMAGES
CREATE TABLE posts_images (
    postsId BIGINT NOT NULL,
    publicId VARCHAR(255) NOT NULL,
    url VARCHAR(512),
    PRIMARY KEY (postsId, publicId),
    CONSTRAINT fk_posts_images_post FOREIGN KEY (postsId) REFERENCES posts(id) ON DELETE CASCADE
);

-- POSTS_FILES
CREATE TABLE posts_files (
    postsId BIGINT NOT NULL,
    publicId VARCHAR(255) NOT NULL,
    url VARCHAR(512),
    PRIMARY KEY (postsId, publicId),
    CONSTRAINT fk_posts_files_post FOREIGN KEY (postsId) REFERENCES posts(id) ON DELETE CASCADE
);

-- POST VOTES
CREATE TABLE postvotes (
    userId BIGINT NOT NULL,
    postId BIGINT NOT NULL,
    vote SMALLINT NOT NULL,
    PRIMARY KEY (userId, postId),
    CONSTRAINT fk_postvotes_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_postvotes_post FOREIGN KEY (postId) REFERENCES posts(id) ON DELETE CASCADE
);

-- SURVEYS
CREATE TABLE surveys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP,
    endDateTime TIMESTAMP,
    type SMALLINT NOT NULL
);

-- SURVEY OPTIONS
CREATE TABLE survey_options (
    surveyId BIGINT NOT NULL,
    optionId INTEGER NOT NULL,
    optionText VARCHAR(255),
    PRIMARY KEY (surveyId, optionId),
    CONSTRAINT fk_survey_options_survey FOREIGN KEY (surveyId) REFERENCES surveys(id) ON DELETE CASCADE
);

-- SURVEY RESPONSES
CREATE TABLE surveyresponses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surveyId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    CONSTRAINT fk_surveyresponses_survey FOREIGN KEY (surveyId) REFERENCES surveys(id) ON DELETE CASCADE,
    CONSTRAINT fk_surveyresponses_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

-- SURVEY RESPONSE OPTIONS
CREATE TABLE survey_response_options (
    surveyResponseId BIGINT NOT NULL,
    optionId INTEGER NOT NULL,
    PRIMARY KEY (surveyResponseId, optionId),
    CONSTRAINT fk_survey_response_options_response FOREIGN KEY (surveyResponseId) REFERENCES surveyresponses(id) ON DELETE CASCADE
);

-- POINT TRANSACTIONS
CREATE TABLE pointtransactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    points INT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    entityType VARCHAR(50),
    entityId BIGINT,
    createdAt TIMESTAMP,
    CONSTRAINT fk_pointtransactions_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);